PROCESS_DIRECTORY: 'process'
MODE: 'process' # either 'process', 'paramsearch_segmentation', or 'paramsearch_read-calling'. 'paramsearch' options override
                # the requested files and tags and performs a small grid search of NUCLEUS_AREA, THRESHOLD_DAPI, and
                # THRESHOLD_CELL ('paramsearch_segmentation'), or of THRESHOLD_READS ('paramsearch_read-calling'). Segmentation
                # parameters should be chosen either manually or by this parameter search prior to running 'paramsearch_read-calling'.
REQUESTED_FILES: ['combined.csv']
# final outputs
REQUESTED_TAGS: [
  # 'cellpose_input.png', # RGB image used as input CellPose model, useful for running CellPose diameter calibration
  'cells.csv',
  'phenotype.csv',
  'annotate_SBS.tif', # LoG image overlayed with base calls
  # 'annotate_SBS_extra.tif', # LoG image overlayed with base calls annotated as mapped/unmapped
  # 'annotate_segment.tif' # first cycle of SBS overlayed with cell and nuclei outlines
]
# discarded after processing to save space
TEMP_TAGS: ['aligned.tif', 'maxed.tif', 'std.tif']

### INPUT TO ANALYSIS
WELL_TILE_LIST: 'input/well_tile_list.csv'
INCLUDE_WELLS_TILES: 'all' # either 'all' or list of [well,tile] pair lists. If running in either paramsearch modes, sites must be restricted to a subset
INPUT_DIRECTORY: 'input'
BARCODE_TABLE: 'barcodes.csv'
MAGNIFICATION: '10X'
SBS_INPUT_TAG: 'sbs.tif'
SBS_CYCLES: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # cycles to include for analysis
SBS_CYCLE_FORMAT: 'c{cycle}-SBS-{cycle}' # python format string

PHENOTYPE_INPUT_TAG: 'phenotype.tif'
PHENOTYPE_CYCLE: 'c0-DAPI-p65ab'

### ANALYSIS PARAMETERS
SEGMENT_METHOD: 'cell_2019' # either 'cell_2019' or 'cellpose'
CELLPOSE: # not used when SEGMENT_METHOD='cell_2019'
  CYTO_CYCLE: -1 # -1 is the last cycle
  CYTO_CHANNEL: 4 # 0-indexed, 4="C" channel from sequencing
  DIAMETER: 14 # calculated by running CellPose calibration (e.g., from their GUI)

# morphological segmentation parameters, not used when SEGMENT_METHOD='cellpose'
NUCLEUS_AREA: [40, 400] # min and max nucleus area in pixels, for paramsearch_segmentation mode can be list of [min,max] lists to test
THRESHOLD_DAPI: 200  # threshold for segmenting nuclei, for paramsearch_segmentation mode can be list of thresholds to test
THRESHOLD_CELL: 600  # threshold for segmenting cells, for paramsearch_segmentation mode can be list of thresholds to test
THRESHOLD_READS: 75  # threshold for detecting reads, for paramsearch_read-calling mode can be list of thresholds to test

MAXED_WIDTH: 3
AUTOSCALE_PHENOTYPE: False # set to True if different microscope binning used for sequencing and phenotype acquisitions
NUCLEUS_PHENOTYPE_FEATURES: [
    'label', # required to join SBS and phenotype data
    'i', 'j', 'area', # named features
    # features defined by channel
    # list of [indexed feature name,output feature name], ops.features.indexed_feature_names
    # e.g., ['c0_mean','dapi_mean'] extracts the mean intensity of channel 0, which in the final table is named 'dapi_mean'
    ['c0_mean', 'dapi_mean'],
    ['c1_mean', 'ha_mean'],
    ['c0_median', 'dapi_median'],
    ['c1_median', 'ha_median'],
    ['c0_max', 'dapi_max'],
    ['c1_max', 'ha_max'],
    ['c0_min', 'dapi_min'],
    ['c1_min', 'ha_min'],
    ['c0c1_corr', 'dapi_ha_corr'],
  ]
CELL_PHENOTYPE_FEATURES: [
    # same format as above
    'label', # required to join SBS and phenotype data
    'area'
  ]

### DISPLAY OPTIONS
DISPLAY_RANGES:
  DAPI: [500, 15000]
  SBS_G: [100, 10000]
  SBS_T: [100, 20000]
  SBS_A: [100, 8000]
  SBS_C: [100, 6000]
LUTS:
  DAPI: 'GRAY'
  SBS_G: 'GREEN'
  SBS_T: 'RED'
  SBS_A: 'MAGENTA'
  SBS_C: 'CYAN'
